Create website-maintenance splash page for old-weather-whaling.
zooniverse/website-maintenance pull request #1
Opened 2017-05-04 20:07 UTC by jelliotartz

A couple of issues:

1. Karla font - currently imported from google fonts via link tag in head. Could these be imported more efficiently?

2. Links to alternate site and discussion page - are these urls correct?

2017-05-04 20:47 UTC, srallen requested changes
Re the questions: using the link tag is fine. @trouille should be able to answer which project should be linked to.

2017-05-04 20:47 UTC, srallen commented on main.css
> +  font-family: Karla;
declare the font targeting `html` instead. You can declare the base size, weight, and line height for the font as well as the fallback: https://developer.mozilla.org/en-US/docs/Web/CSS/font?v=example

In this case, something like this: `font: 400 16px/1.5 "Karla", sans-serif`

2017-05-04 20:47 UTC, srallen commented on index.html
> +    <img src="img/shape.svg">
Set this as a background image in the CSS instead. Check out the `background-image` and `background-repeat` properties.

2017-05-04 20:47 UTC, srallen commented on main.css
> +  position: absolute;
Once the SVG logo is set as the background, you won't need to absolutely position this.

2017-05-04 20:47 UTC, srallen commented on main.css
> +  position: absolute;
Check out the flex spec for centering content. It's super easy when you get the hang of it: https://www.kirupa.com/html5/centering_vertically_horizontally.htm

2017-05-04 20:47 UTC, srallen commented on main.css
> +.link-text {
Links should have an indication of state change on hover and on focus for accessibility. Easiest is to make the color slightly lighten and you can target these using the `:hover` and `:focus` pseudo-classes.

2017-05-04 20:47 UTC, srallen commented on index.html
> +        Old Weather Whaling is currently down for maintenance. <br>
Something wrong with the period at the end of the sentence. Delete it and make sure it's just text?

2017-05-04 20:47 UTC, srallen commented on index.html
> +      <div class="title">OLD WEATHER WHALING</div>
You can make caps using CSS using `text-transform: uppercase`

2017-05-04 21:15 UTC, trouille commented
@jelliotartz The Discussion Forum link should point to https://www.zooniverse.org/projects/zooniverse/old-weather/talk 

(it's the only way people will be able to access that discussion forum while the site is down. I don't expect much traffic, if any there, but good to give access). 

The other link (to https://www.oldweather.org/) is correct. From there, people can navigate to http://forum.oldweather.org/, so we don't need to link to that discussion forum in the maintenance page. 

Thanks!

2017-05-05 16:48 UTC, srallen commented on main.css
>    font: 400 16px/1.5 Karla, sans-serif;
This should be applied to `html` rather than a class.

2017-05-05 16:48 UTC, srallen commented on main.css
> +  margin: 3vw;
`vw` is a width unit and this is setting it all around. How about: `margin: 1em 3vw`?

2017-05-08 15:32 UTC, srallen commented
This looks ready for use, but as we discussed, the branch won't be merging into master and we'll keep this as a styled project specific version.

2017-05-08 15:32 UTC, closed without merging

2017-05-09 09:03 UTC, astopy commented
Could we maybe put the project specific versions in folders and keep them all in master? (Similar to the [retirement pages](https://github.com/zooniverse/retirement))